// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kchrfvuuwksszlvpjafg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaHJmdnV1d2tzc3psdnBqYWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjIzOTEsImV4cCI6MjA2MzczODM5MX0.Nu4llfg_OaY4y9rD6e4YMJJTGmaLK2rPni8rfdoZfpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);